# app/services/pdf_report.py

from typing import Any, Dict, List
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

# Update pdf_report.py to handle all new categories

def generate_pdf(ui: Dict[str, Any], out_path: str) -> str:
    doc = SimpleDocTemplate(out_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []
    
    # Title
    elements.append(Paragraph("Laméco Document Style Checker Report", styles["Title"]))
    elements.append(Spacer(1, 10))
    
    # Document info
    elements.append(Paragraph(
        f"<b>Document:</b> {ui.get('document')}<br/>"
        f"<b>Date:</b> {ui.get('created_at')}<br/>"
        f"<b>Compliance Score:</b> {ui.get('score')}%<br/>"
        f"<b>Total Issues:</b> {ui.get('counts', {}).get('total', 0)} "
        f"(High: {ui.get('counts', {}).get('high', 0)}, "
        f"Medium: {ui.get('counts', {}).get('medium', 0)}, "
        f"Low: {ui.get('counts', {}).get('low', 0)})",
        styles["Normal"]
    ))
    
    elements.append(Spacer(1, 20))
    
    # Summary table by category
    categories = ui.get('category_counts', {})
    if categories:
        cat_data = [["Category", "High", "Medium", "Low", "Total"]]
        for cat, counts in categories.items():
            total = counts.get('high', 0) + counts.get('medium', 0) + counts.get('low', 0)
            if total > 0:
                cat_data.append([
                    cat,
                    str(counts.get('high', 0)),
                    str(counts.get('medium', 0)),
                    str(counts.get('low', 0)),
                    str(total)
                ])
        
        if len(cat_data) > 1:
            cat_table = Table(cat_data, colWidths=[120, 60, 60, 60, 60])
            cat_table.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
                ("GRID", (0,0), (-1,-1), 0.5, colors.black),
                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ]))
            elements.append(Paragraph("<b>Issues by Category</b>", styles["Normal"]))
            elements.append(Spacer(1, 5))
            elements.append(cat_table)
            elements.append(Spacer(1, 20))
    
    # Detailed findings table
    elements.append(Paragraph("<b>Detailed Findings</b>", styles["Normal"]))
    elements.append(Spacer(1, 10))
    
    table_data = [["Location", "Category", "Severity", "Message", "Details"]]
    
    for f in ui.get("findings", []):
        # Truncate long text for PDF
        location = f.get("location", "")[:20]
        category = f.get("category", "")[:15]
        severity = f.get("severity", "")[:10]
        message = f.get("message", "")[:40]
        detail = f.get("detail", "")[:30]
        
        table_data.append([location, category, severity, message, detail])
    
    table = Table(table_data, colWidths=[70, 70, 50, 150, 100], repeatRows=1)
    
    # Table style
    style = TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("GRID", (0,0), (-1,-1), 0.5, colors.black),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 8),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.whitesmoke]),
    ])
    
    # Color code by severity
    for i, f in enumerate(ui.get("findings", []), start=1):
        sev = f.get("severity")
        if sev == "high":
            style.add("BACKGROUND", (0,i), (-1,i), colors.salmon)
        elif sev == "medium":
            style.add("BACKGROUND", (0,i), (-1,i), colors.lightyellow)
        elif sev == "low":
            style.add("BACKGROUND", (0,i), (-1,i), colors.lightgreen)
    
    table.setStyle(style)
    elements.append(table)
    
    # Legend
    elements.append(Spacer(1, 15))
    legend_elements = []
    legend_elements.append(Paragraph(
        "<b>Legend:</b>",
        styles["Normal"]
    ))
    legend_elements.append(Spacer(1, 5))
    
    legend_data = [
        ["High Priority", "Critical issues that must be fixed"],
        ["Medium Priority", "Issues that should be fixed"],
        ["Low Priority", "Minor issues or suggestions"]
    ]
    
    legend_table = Table(legend_data, colWidths=[80, 300])
    legend_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,0), colors.salmon),
        ("BACKGROUND", (0,1), (0,1), colors.lightyellow),
        ("BACKGROUND", (0,2), (0,2), colors.lightgreen),
        ("GRID", (0,0), (-1,-1), 0.5, colors.black),
    ]))
    elements.append(legend_table)
    
    # Footer
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        f"<i>Report generated by Laméco AI Style Checker on {datetime.now().strftime('%Y-%m-%d %H:%M')}</i>",
        styles["Italic"]
    ))
    
    doc.build(elements)
    return out_path